CA-2039 Suppress cpu level logging if not available (or not rooted)
rfcx/rfcx-guardian-android pull request #13
Opened 2020-02-28 18:28 UTC by Tooseriuz

2020-03-01 15:04 UTC, antonyharfield requested changes
Lots of good changes. :)

Important to fix the bluetooth setOn to only be when the preferences are set.

2020-03-01 15:04 UTC, antonyharfield commented on admin/src/main/java/org/rfcx/guardian/admin/RfcxGuardian.java
> +		DeviceBluetooth.setOn();
There is a preference `admin_enable_bluetooth`. We should check that this is `true` before we call `setOn()`.

2020-03-01 15:04 UTC, antonyharfield commented on admin/src/main/java/org/rfcx/guardian/admin/activity/MainActivity.kt
> +        if(::monitorTimer.isInitialized){
Please fix code style.

2020-03-01 15:04 UTC, antonyharfield commented on core/src/main/java/org/rfcx/guardian/utility/device/DeviceCPU.java
> +		if (DeviceRoot.isRooted()) {
Large blocks of code inside an `if` is a code smell.

You could rewrite this as:
```
if (! DeviceRoot.isRooted()) {
    return 0;
}
...
```

2020-03-01 15:04 UTC, antonyharfield commented on core/src/main/java/org/rfcx/guardian/utility/device/DeviceCPU.java
> +			}
This code hasn't changed so it shouldn't be in git.

I think you have your Android Studio setup incorrectly @Tooseriuz -- you have converted 4 spaces into tabs. Please use 4 spaces to be consistent with the rest of the code.

2020-03-01 15:04 UTC, antonyharfield commented on core/src/main/java/org/rfcx/guardian/utility/device/DeviceRoot.java
> +        if(buildTags != null && buildTags.contains("test-keys")) {
Fix code style `if(`

2020-03-01 15:04 UTC, antonyharfield commented on core/src/main/java/org/rfcx/guardian/utility/device/DeviceRoot.java
> +        } else {
The `else` is not required.

2020-03-01 15:04 UTC, antonyharfield commented on guardian/src/main/java/org/rfcx/guardian/guardian/utils/CheckAppPermissionUtils.kt
> +    fun checkLocationPermission(context: Context): Boolean{
Code style `Boolean{`

2020-03-01 17:24 UTC, antonyharfield requested changes
Let's remove the indent changes... it is better if the pull request is ONLY the changes related to the pull request.

2020-03-02 05:40 UTC, antonyharfield approved these changes
Ok - good to merge!

2020-03-02 05:51 UTC, Debjani1989 commented
Hello Rfcx/Rfcx-Guardian-Android team,

How are you doing? This is to inform you that I am not a part of this
operation anymore, but I am still a big fan and well wisher of rfcx and
Topher, no doubt. So would u please remove my email from the list? I am
getting continuous notification of the communication.

Thank you very much
Debjani Shyama
Social Media Associate
64-65 Kazi Nazrul Islam Avenue, Dhaka-1215, Bangladesh
Phone:01788 198233



On Mon, Mar 2, 2020 at 11:40 AM Antony Harfield <notifications@github.com>
wrote:

> *@antonyharfield* approved this pull request.
>
> Ok - good to merge!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rfcx/rfcx-guardian-android/pull/13?email_source=notifications&email_token=ACA4UYPCYVOMW462BRY73BDRFNBDLA5CNFSM4K5XNE6KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCXPVZIA#pullrequestreview-366959776>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACA4UYNZO3GHM3U5CYS7SZTRFNBDLANCNFSM4K5XNE6A>
> .
>

2020-03-02 12:15 UTC, Tooseriuz commented
Hi @Debjani1989,
You can unsubscribe this repository by choose unwatch here
![image](https://user-images.githubusercontent.com/44440424/75675625-15584400-5cba-11ea-8119-0e22affc89fc.png)

2020-03-02 12:15 UTC, merged