CA-2052 Add safety check to reboot after 30 minutes of no GSM connection
rfcx/rfcx-guardian-android pull request #14
Opened 2020-02-29 19:20 UTC by Tooseriuz

2020-03-01 15:11 UTC, antonyharfield commented
Sorry @Tooseriuz, we will hold this for now as @topherwhite has a better solution that reuses the failure checks in the ApiCheckInService.

2020-03-05 17:41 UTC, Tooseriuz commented
@antonyharfield from the diff that you provided in Jira, we do not need this PR anymore if that is working.

2020-03-08 11:05 UTC, antonyharfield requested changes

2020-03-08 11:05 UTC, antonyharfield commented on core/src/main/java/org/rfcx/guardian/utility/device/DeviceMobilePhone.java
> +	}
I don't understand why these are 2 separate methods. Isn't it better as 1?

2020-03-08 11:05 UTC, antonyharfield commented on core/src/main/java/org/rfcx/guardian/utility/device/DeviceCPU.java
> +		}
These lines have not changed... try not to commit them.

Use the technique I suggested before:

```
if (!DeviceRoot.isRooted()) {
   return 0;
}
```

2020-03-08 11:05 UTC, antonyharfield commented on admin/src/main/java/org/rfcx/guardian/admin/activity/MainActivity.kt
> +        if(::monitorTimer.isInitialized){
Style.

2020-03-08 11:05 UTC, antonyharfield commented on admin/src/main/java/org/rfcx/guardian/admin/RfcxGuardian.java
> +		DeviceBluetooth.setOn();
As commented before, should be inside an if to check the pref.

2020-03-08 12:32 UTC, antonyharfield approved these changes
Looks good now.

2020-03-09 14:59 UTC, topherwhite approved these changes
looks good to me and thanks for using the thresholds!

2020-03-10 12:08 UTC, merged