Not record diagnostic during sleep
rfcx/rfcx-guardian-android pull request #184
Opened 2022-03-15 09:01 UTC by Tooseriuz

Resolve #169 
- Add new preference for admin telemetry capturing off hours
- Not record for both i2c and system

2022-03-21 04:25 UTC, antonyharfield requested changes
What happens if the diagnostics are off while the Companion is connected?

2022-03-21 04:25 UTC, antonyharfield commented on lib-core/src/main/java/org/rfcx/guardian/utility/misc/TimeUtils.kt
> +            if (DateTimeUtils.isTimeStampWithinTimeRange(Date(), offHours[0], offHours[1])) {
This is poor! Where have you checked that there are at least 2 elements in the array?

2022-03-21 08:00 UTC, Tooseriuz commented
@antonyharfield it uses separated processes for diagnostic snapshot and companion ping snapshot

2022-03-28 09:42 UTC, antonyharfield approved these changes

2022-03-28 09:47 UTC, merged