Python script for playing sounds on RPi for E2E tests
rfcx/rfcx-guardian-android pull request #192
Opened 2022-03-24 05:17 UTC by KritsanaMike

python script for playsound

2022-03-25 02:04 UTC, antonyharfield requested changes
Can we make this part of the CLI? E.g. `cli sounds`

2022-03-25 02:04 UTC, antonyharfield commented on playsound/play_sound.py
> +        time.sleep(1)
Should sleep be called on every iteration of the while loop?

2022-03-25 02:04 UTC, antonyharfield commented on playsound/play_sound.py
> +    name = ['dog','truck','motorcycle','chainsaw']
If you hardcode the files then you need to change the script for every new file. Instead, scan the current directory for wav files.

2022-03-25 02:04 UTC, antonyharfield commented on playsound/play_sound.py
> +    name = ['dog','truck','motorcycle','chainsaw']
You could scan for files when the program starts, and display an error if none are found.

2022-03-28 11:15 UTC, KritsanaMike commented on playsound/play_sound.py
> +    name = ['dog','truck','motorcycle','chainsaw']
I fixed them. check them for me, please.

2022-03-28 12:31 UTC, antonyharfield approved these changes

2022-03-30 09:08 UTC, Tooseriuz commented on playsound/play_sound.py
> +    return file
naming `file` as `files` would be better since we expect it to be list of files

2022-03-30 09:09 UTC, Tooseriuz commented on playsound/play_sound.py
> +    return file
and function name would be `getFiles` or `readFiles`

2022-03-30 09:11 UTC, Tooseriuz commented on playsound/play_sound.py
> +        playsound(path+ran)
- since we are getting list of files then `name` should be `files`
- `ran` should be `file` since we randomly pick a file
- better to have white space between `+` `print("Playing..." + file)`

2022-03-30 09:39 UTC, Tooseriuz commented on playsound/play_sound.py
> +    t_min = result.tm_min
- better to have white space between + 
- naming `result` to `system_time` or `local_time`

2022-03-30 09:57 UTC, Tooseriuz commented on playsound/play_sound.py
> +    time.sleep(10)
you could refactor logic to 
```
if t_hr > 22:
   continue
if t_min != 0 or t_min != 30:
   continue
if t_hr == 22 and t_min > 0:
   continue
print(t_hr)
play_sound() 
```

2022-03-30 09:58 UTC, Tooseriuz requested changes
some naming and refactor for better readability

2022-04-01 09:18 UTC, KritsanaMike commented on playsound/play_sound.py
> +    return file
> naming `file` as `files` would be better since we expect it to be list of files
Ok. I will fix this name

> and function name would be `getFiles` or `readFiles`
and this one too

2022-04-01 09:34 UTC, KritsanaMike commented on playsound/play_sound.py
> +    time.sleep(10)
> you could refactor logic to
> 
> ```
> if t_hr > 22:
>    continue
> if t_min != 0 or t_min != 30:
>    continue
> if t_hr == 22 and t_min > 0:
>    continue
> print(t_hr)
> play_sound() 
> ```

I think this logic does not support, cause we have to start play at 9 AM and finish at 10 PM. but your logic that look like play every time is not more than 10 PM

2022-04-06 08:51 UTC, Tooseriuz approved these changes

2022-04-06 08:51 UTC, merged