Python cli
rfcx/rfcx-guardian-android pull request #195
Opened 2022-03-25 07:53 UTC by KritsanaMike

add cli for get information from i2c and swarm tile

2022-03-25 09:57 UTC, antonyharfield requested changes

2022-03-25 09:57 UTC, antonyharfield commented on cli/commands/swarm.py
> +    result = execute(device, '$GS @*74')
Let's calculate the checksum automatically. This line should be:

```
result = execute(device, 'GS @')
```

The `$` and the `*XX` should be added by the execute command.

2022-03-25 09:57 UTC, antonyharfield commented on cli/commands/adb_guardian.py
> +    # ECHO Input Voltage -
?

2022-03-25 09:57 UTC, antonyharfield commented on cli/commands/i2c.py
> +def status(): # TODO Get i2c status
Remove `TODO`

2022-03-28 12:44 UTC, antonyharfield reviewed
Good progress!

There are a few bits of logic in the UI and CLI that I think can be refactored to 1 place. E.g. when getting a message from swarm we can use the same code to remove the checksum and parse the message.

2022-03-28 12:44 UTC, antonyharfield commented on cli/README.md
> +- `ui` Show ui .exe file
The UI is not related to `.exe` file.

2022-03-28 12:44 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +        raise ValueError("The NMEA data does not match it's checksum")
Not being used?

2022-03-28 12:44 UTC, antonyharfield commented on cli/commands/swarm.py
> +    if sw_status[0] == "0011010-1":
Refactor: This logic is needed in UI and CLI.

2022-03-28 12:44 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +        if i >= 0: break
This is confusing... it adds the $ and then try to remove it in the loop.

2022-03-28 12:44 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +        return (False, None, None)
I don't see where (False, None, None) is needed.

2022-03-30 10:14 UTC, Tooseriuz commented on cli/commands/common/i2c_command.py
> +def battery_cuurent(device):
`cuurent` to `current`

2022-03-30 10:15 UTC, Tooseriuz commented on cli/commands/common/swarm_command.py
> +    validated_lines = [validate_checksum(line) for line in lines]
I don't think we need to validate checksum on result of the command tho

2022-03-30 11:20 UTC, Tooseriuz requested changes
not sure why we need to validate checksum when getting result back from command

2022-04-01 09:53 UTC, KritsanaMike commented on cli/commands/common/swarm_command.py
> +    validated_lines = [validate_checksum(line) for line in lines]
for this and help me to write the code. and I think we validate checksum because the value from swarm will include $ and *. if we put into check we will get real value

2022-04-01 10:13 UTC, antonyharfield requested changes

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/i2c_command.py
> +        return False
`return i2c_status == "0x0001"`

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/i2c_command.py
> +        return None
Ewww... the 4 lines are the same as `return response`

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/i2c_command.py
> +    input_v = result[0:6]
Avoid duplicating code.

You do this on every command, so it can be moved into `execute`.

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/i2c_command.py
> +    input_v = int(input_v, 16)*1.648
Also do this on every command `int(x, 16)`. Move it inside.

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/i2c_command.py
> +    input_c = int(input_c, 16)*(0.00146487 /0.005)
Inconsistent spacing.

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +    validated_lines = [validate_checksum(line) for line in lines]
@Tooseriuz Validate checksum helps be confident that a corrupt message was not sent.

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +    return value
Same as:
```
   for v in validated_lines:
         if v.startswith(prefix):
             return v
   return None
```

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +    return value
Avoid creating unnecessary variables.

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +    # return [line for line in validated_lines if line.startswith(prefix)][0]
Avoid committing commented code.

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +        return None
When using `return` in `if`, you can:
```
if swarm_fw != None:
   return str(swarm_fw.split(" ")[1])
return None
```

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/common/swarm_command.py
> +        return "None" # startswith method cannot check None value
Ugly!

If your code to detect `None` before calling `startswith`.

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/i2c.py
> +    else :
Inconsistent space before :

2022-04-01 10:13 UTC, antonyharfield commented on cli/commands/i2c.py
> +    typer.echo("System voltage: " + typer.style(sys_v, fg=typer.colors.GREEN, bold=True))
float => string => float 😱

Suggest:
```
typer.echo("System voltage: " + typer.style("{:.2f}".format(sys_v), fg=typer.colors.GREEN, bold=True))
```

2022-04-06 09:06 UTC, Tooseriuz approved these changes

2022-04-06 09:07 UTC, merged