Swarm messaging meta
rfcx/rfcx-guardian-android pull request #91
Opened 2021-10-15 08:07 UTC by Tooseriuz

## Summary

- resolve #90 
- Add command to get unsent message number
- Add timeout back to command execution because `MT` command require >1 second to get response back
- Include that number into meta blob
- Compress `swm_diagnostic` if satellite values are default then remove it

`1634274527683*-88*0*0*0*1970-01-01 00:00:00*0x000000*0` to `1634274527683*-88*0`

2021-10-15 08:31 UTC, antonyharfield requested changes

2021-10-15 08:31 UTC, antonyharfield commented on role-admin/src/test/java/org/rfcx/guardian/admin/comms/swm/SwmApiMTTest.kt
> +        val dateTime = api.getNumberOfUnsentMessages()
`dateTime`!

2021-10-15 08:31 UTC, antonyharfield commented on role-admin/src/main/java/org/rfcx/guardian/admin/contentprovider/AdminContentProvider.java
> +                    return RfcxComm.getProjectionCursor(appRole, "database_get_all_rows", new Object[]{"swm_diagnostic", SwmUtils.getSwmMetaValuesAsJsonArray(app.getApplicationContext()).toString(),
Sorry, I've changed my mind about this... I think `swm` is better as it is fewer characters to send.

2021-10-15 08:31 UTC, antonyharfield commented on role-admin/src/main/java/org/rfcx/guardian/admin/comms/swm/SwmMetaDb.java
> +        }
Doing it like this is dangerous because if we add a new field then it might break. On the server, I will only support 2 cases as we discussed:
- `1634274527683*-88*0` - background + unsent
- `1634274527683*-88*0*0*0*1970-01-01 00:00:00*0x000000*0` background + satellite x4 + unsent

2021-10-15 08:31 UTC, antonyharfield commented on role-admin/src/main/java/org/rfcx/guardian/admin/comms/swm/SwmUtils.kt
> +                metaJson.put("diagnostic", app.swmMetaDb.dbSwmDiagnostic.concatRowsIgnoreNull)
Should this be `swm_diagnostic`? See comment below about renaming to `swm`.

2021-10-19 09:17 UTC, antonyharfield approved these changes

2021-10-19 09:17 UTC, antonyharfield commented on role-admin/src/main/java/org/rfcx/guardian/admin/comms/swm/api/SwmApi.kt
> +        } ?: 0
If we don't get a result then should we set it to `-1`?

2021-10-19 09:17 UTC, antonyharfield commented on role-admin/src/main/java/org/rfcx/guardian/admin/comms/swm/api/SwmUartShell.kt
> +        return "echo -n '${input}\\r' | $busyboxBin microcom -t ${timeout}000 -s $baudRate $ttyPath"
I still think that `busybox timeout` in here will make the command safer. Imagine the situation where the tile starts sending lots of messages every second, then this command will never exit.

2021-10-19 09:17 UTC, antonyharfield commented on role-guardian/src/main/java/org/rfcx/guardian/guardian/asset/meta/MetaJsonUtils.java
> +			RfcxComm.deleteQuery("admin", "database_delete_rows_before", "swm_diagnostic|" + deleteBefore.getTime(), app.getResolver());
Is this still correct? I'm not sure.

2021-10-19 09:23 UTC, Tooseriuz commented on role-guardian/src/main/java/org/rfcx/guardian/guardian/asset/meta/MetaJsonUtils.java
> +			RfcxComm.deleteQuery("admin", "database_delete_rows_before", "swm_diagnostic|" + deleteBefore.getTime(), app.getResolver());
it is just content provider command for Admin role.

2021-10-19 09:24 UTC, Tooseriuz commented on role-admin/src/main/java/org/rfcx/guardian/admin/comms/swm/api/SwmUartShell.kt
> +        return "echo -n '${input}\\r' | $busyboxBin microcom -t ${timeout}000 -s $baudRate $ttyPath"
yea but I think we should hold it like this first and see how it is working when i am away

2021-10-19 09:24 UTC, Tooseriuz commented on role-admin/src/main/java/org/rfcx/guardian/admin/comms/swm/api/SwmApi.kt
> +        } ?: 0
Agree with this

2021-10-19 09:53 UTC, merged